Update fail_fast.yml

diff --git a/.github/workflows/fail_fast.yml b/.github/workflows/fail_fast.yml
--- a/.github/workflows/fail_fast.yml
+++ b/.github/workflows/fail_fast.yml
@@ -20,7 +20,7 @@ jobs:
       - name: Job 2
         run: |
           sleep 10
-          exit 0
+          exit 1
           
       - name: Cancelling parallel jobs
         if: failure()
@@ -39,21 +39,25 @@ jobs:
         uses: andymckay/cancel-action@0.3
   
   
-  check_results:
+  get_results: 
     runs-on: ubuntu-latest
     needs: [job1, job2, job3]
-    if: always()
-    steps:
-      - name: Sent Slack message
+    if: ${{ !cancelled() }}
+    steps:          
+      - name: Prepare result status
+        shell: bash
+        id: prepare_status
+        env:
+          context: ${{ toJSON(needs) }}
         run: |
-          echo "I'm a Slack message"
-          
-      - name: Check Job Results
-        run: |
-          if [[ needs.job1.outputs.result != '0' || needs.job2.outputs.result != '0' || needs.job3.outputs.result != '0' ]]; then
-            echo "One or more jobs failed. Failing the build."
+          echo $context | jq --color-output .
+
+          rc_failed=${{ contains(join(needs.*.result, ','), 'failure') || contains(join(needs.*.result, ','), 'cancelled')}}
+          echo "RC failed?: $rc_failed"
+
+          if [ $rc_failed == 'true' ]; then
+            echo "emoji=:redex:" >> $GITHUB_OUTPUT
             exit 1
           else
-            echo "All jobs passed."
+            echo "emoji=:green_heart:" >> $GITHUB_OUTPUT
           fi
-
