Update mark_failed_step.yml

diff --git a/.github/workflows/mark_failed_step.yml b/.github/workflows/mark_failed_step.yml
--- a/.github/workflows/mark_failed_step.yml
+++ b/.github/workflows/mark_failed_step.yml
@@ -16,12 +16,7 @@ jobs:
         continue-on-error: true
         run: |
           cat 42
-          if [ $? -eq 0 ]; then
-            echo "Script completed successfully"
-          else
-            echo "::error::Script failed!"
-          fi
-          # [ $? -ne 0 ] && echo "::error::Script failed!"
+          [ $? -ne 0 ] && echo "::error:: Script failed!"
 
       - name: With error and canceled
         if: ${{ !cancelled() }}
