Update mark_failed_step.yml

diff --git a/.github/workflows/mark_failed_step.yml b/.github/workflows/mark_failed_step.yml
--- a/.github/workflows/mark_failed_step.yml
+++ b/.github/workflows/mark_failed_step.yml
@@ -16,7 +16,7 @@ jobs:
         continue-on-error: true
         run: |
           cat 42
-          # [ $? -ne 0 ] && echo "::error::Script failed!"
+          [ $? -ne 0 ] && echo "::error::Script failed!"
 
       - name: Simple error
         run: |
