Update rc.yml

diff --git a/.github/workflows/rc.yml b/.github/workflows/rc.yml
--- a/.github/workflows/rc.yml
+++ b/.github/workflows/rc.yml
@@ -20,7 +20,7 @@ jobs:
       - name: Failed job
         shell: bash
         run: |
-          exit 0
+          exit 1
   context:
     runs-on: ubuntu-latest
     steps:
@@ -80,18 +80,38 @@ jobs:
     needs: [first_job, second_job]
     if: ${{ !cancelled()  }}
     steps:          
+      - name: Prepare data
+        id: prepare_status
+        shell: bash
+        run: |
+          status=$(echo "${{ needs.*.result }}" | grep "failure")
+          echo "Status: $status"
+          echo "rc-status=$status" >> $GITHUB_ENV
+    
+          if [ -n "$status" ]; then
+             echo "emoji=':redex:'" >> $GITHUB_ENV
+          else 
+            echo "emoji=':green_heart:'" >> $GITHUB_ENV
+          fi
+
+    
       - name: Report failure to Slack
         if: ${{ contains(join(needs.*.result, ','), 'failure') }}
         shell: bash 
         run: |
           echo "RC <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|${{github.run_id}}> with ${GITHUB_SHA::7} is :redex:."
           echo "Login ${{ github.event.pusher.name }}"
-          echo "${GITHUB_SHA}|${GITHUB_SHA::7}"
+
       - name: Report success to Slack
         if: ${{ !contains(join(needs.*.result, ','), 'failure') }}
         shell: bash 
         run: |
           echo "Login ${{ github.event.pusher.name }}"
-          echo "RC <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|${{github.run_id}}> with <https://github.com/${{github.repository}}/commit/${GITHUB_SHA}|${GITHUB_SHA::7}> (PR # by ${{github.event.pusher.name}}) is :redex:."
+          echo "RC <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|${{github.run_id}}> with <https://github.com/${{github.repository}}/commit/${GITHUB_SHA}|${GITHUB_SHA::7}> (PR # by ${{github.event.pusher.name}}) is ${{env.emoji}}."
           echo "RC <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|${{github.run_id}}> with ${GITHUB_SHA::7} is :green_heart:."
-          echo "${GITHUB_SHA}|${GITHUB_SHA::7}"
+
+      - name: Report success to Slack
+        shell: bash 
+        run: |
+          echo "RC <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|${{github.run_id}}> with <https://github.com/${{github.repository}}/commit/${GITHUB_SHA}|${GITHUB_SHA::7}> (PR # by ${{github.event.pusher.name}}) is ${{env.emoji}}."
+
