Update rc.yml

diff --git a/.github/workflows/rc.yml b/.github/workflows/rc.yml
--- a/.github/workflows/rc.yml
+++ b/.github/workflows/rc.yml
@@ -44,39 +44,31 @@ jobs:
   get_results: 
     runs-on: ubuntu-latest
     needs: [first_job, second_job, third_job]
-#     if: ${{ !cancelled() && needs.first_job.result != 'skipped' && needs.second_job.result != 'skipped'  && needs.third_job.result != 'skipped'}}
-    if: ${{ !cancelled() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'skipped') }}
-
+    if: ${{ !cancelled() }}
     steps:          
-      - name: JSON needs
-        run: |
-          echo $context | jq --color-output .
+      - name: Prepare result status
+        shell: bash
+        id: prepare_status
         env:
           context: ${{ toJSON(needs) }}
-   
-      - name: Report failure to Slack
-        if: ${{ contains(join(needs.*.result, ','), 'failure') }}
-        shell: bash 
         run: |
-          echo "RC <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|${{github.run_id}}> with ${GITHUB_SHA::7} is :redex:."
-          echo "Login ${{ github.event.pusher.name }}"
+          echo $context | jq --color-output .
 
-      - name: Report success to Slack
-        if: ${{ !contains(join(needs.*.result, ','), 'failure') }}
-        shell: bash 
-        run: |
-          echo "Login ${{ github.event.pusher.name }}"
-          echo "RC <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|${{github.run_id}}> with <https://github.com/${{github.repository}}/commit/${GITHUB_SHA}|${GITHUB_SHA::7}> (PR # by ${{github.event.pusher.name}}) is ${{env.emoji}}."
-          echo "RC <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|${{github.run_id}}> with ${GITHUB_SHA::7} is :green_heart:."
+          rc_failed=${{ contains(join(needs.*.result, ','), 'failure') || contains(join(needs.*.result, ','), 'cancelled')}}
+          echo "RC failed?: $rc_failed"
 
-      - name: Report success to Slack
- 
-        shell: bash 
+          if [ $rc_failed == 'true' ]; then
+            echo "emoji=:redex:" >> $GITHUB_OUTPUT
+            exit 1
+          else
+            echo "emoji=:green_heart:" >> $GITHUB_OUTPUT
+          fi
+          
+      - name: Post always
+        if: always()
+        shell: bash
         run: |
-          echo "RC <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|${{github.run_id}}> with <https://github.com/${{github.repository}}/commit/${GITHUB_SHA}|${GITHUB_SHA::7}> (PR # by ${{github.event.pusher.name}}) is ${{steps.prepare_status.outputs.emoji}}."
- 
-  trigger-job:
-    uses: ./.github/workflows/inputs_test.yml
+           echo 'Uouououhhuhu'
   
   context:
     runs-on: ubuntu-latest
